language: php

php:
  - 7.2
  - 7.3

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - ~/cphalcon

install:
  - composer self-update
  - cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install
  - cp -v /home/scrutinizer/cphalcon/build/php7/64bits/modules/phalcon.so  /home/scrutinizer/.phpenv/versions/7.2.13/lib/php/extensions/no-debug-zts-2017071
  - test -e /home/scrutinizer/cphalcon/build/php7/64bits/modules/phalcon.so
  - sed -i '$ a \\n[Phalcon]\nextension=phalcon.so\n' /home/scrutinizer/.phpenv/versions/7.2.13/etc/php.ini
  - php -m | grep -i Phalcon
  - sudo /etc/init.d/apache2 restart
  - composer update --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE baka CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;' -uroot
  - cat tests/_data/dump.sql | mysql -uroot baka
