language: php

php:
  - 7.2
  - 7.3

services:
  - mysql
  - memcached
  - redis-server
  - rabbitmq

addons:
  apt:
    packages:
    - rabbitmq-server

sudo: false

env:
  global:
      - DATA_API_MYSQL_HOST: "127.0.0.1"
      - DATA_API_MYSQL_PASS: ""
      - DATA_API_MYSQL_USER: "root"
      - DATA_API_MYSQL_NAME: "gonano"
      - DATA_API_MEMCACHED_HOST: "127.0.0.1"
      - DATA_API_MEMCACHED_PORT: 11211
      - DATA_API_MEMCACHED_WEIGHT: 100
      - REDIS_HOST: "127.0.0.1"
      - REDIS_PORT: 6379
      - APP_IP: "api.baka.ld"
      - APP_ENV: development
      - JWT_SECURITY: 0
      - GEWAER_APP_ID: 1
      - PHINX_CONFIG_DIR: "/home/scrutinizer/build/storage"
      - secure: "t8WqAm/a0MROeVmN4qSEdpJ59XQB8AuwR5TqpTB8g8v9lr5ioZE1TouogZERXrZLqs2u8IQZow06pYAXAbfgpLvHPy64CglkG4gD1827CJFtmlUe4X9XFQ0o3jRtEPPdCr8dUqKXkJroOus2/hoMNrTaQ+xCKhvFiXpvRlZTuLWr8wj7lhID3HXkmnGFkmB+n1gtiBbEmyXSxDFKQh3iDs3QJ6f4WKUI7j4AtdWBtoxdMgFDYsY1eRaTXivNDvKxXJIiuVt0oLtiEm4qExX5+7XZ1OLGQebW8b2ZGnb/mAhSUBI3UfAa0dXx4ih3JPgwuySzm4iqPnIeGIk8M8ad6EaXOjf00AP5loqOrqGXmsuzv0a8+rN6R/sz0v2buJm/2Rf6GJp1xKQJFr0wvsR1vGpNAwfoOMzpN9YG7CtFYtwPYANQXLydUFZYBo5UBpGd8QVNjuRCJTAyH/NaFlDwJB03LPOv5np+GCDNO1Toh+EHn/lpNATHa+uaJpvfhHkzbUoHaOEYdcECnAkwttbI23WPU6u531rUoJv+wKbAzfHQES6vVhqYBP6Ts0p+31i7SFuLBz0AvBWy9+Jxy70fp686p4g8cgvjAOklocBdZo4ErSXv2pKD/WobuXZfr+V/50wSfa5aSFCImUMlhD6QNLO5bvt6ZXo2w+4M4vbR0eU="
      - secure: "QzSOjdNBBeNkqOhjURare097yO4RRnBsqb4ktAYRkYYLm0k9MQqlPTqkF6tMkVRw+YJIkoXZc8iGqEhyvjijvIjLaZ1d+EHv7aOzaMiXvFAoluT20/CR0www5gydlgGbZRS6kfPOvi7+cvFNGaXwL/wUZuGmT9dOvFYdkwV0ARUvf/gikuza0KfGOqIpFNzZE8NtrYZb241IViUvn+wo9i34h97VzTwcLKkKCID4ni2GC7RMNNvO4Fjp09BKDfioucV83T7mgbPRewIlovtqYc/OTIcL/UqOWf/+01Kv5ItEc5ZbU0WaM+cloBrXbBj5mPGeOcHj3fObO8t7vAmWCIkESxr/+1xQkpfVSVLwC3JD6g8DpYiPoqbroTpUMFgAnKstgc5LXdZpBYyOLlqwwF99yCWzLE8SL/XwWIbZIKW+2ewZhOe5KzOTlD18+vVskejy0pCjp1msHNFOxFSmklTuNnLSpEYtY1Nr+QTiAmno+2kQu0VlBfhNIX/YafQ/qXSiMBuB+faqYf7srN1mcWwm9+FKiXFSr0le5HlBQp9WgmqeyC8M/rmn8vsmd4wOCyZ5Zgrsph+L2+XCaCrLdKXffDw1TKUqU3pJwdOPHsukjYoPGsL69JpJthVfyGatrY785kkc1f6uXJX1YtsQgvnMGKXzKY/F709EwjwpsqQ="

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - ~/cphalcon

install:
  - composer self-update
  - cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install
  - echo 'extension = "phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php --ri phalcon

before_script:
  - cd $TRAVIS_BUILD_DIR
  - cp storage/ci/.env.example .env
  - cp storage/ci/phinx.php.example phinx.php
  - mysql -e "CREATE DATABASE gonano"
  - sudo redis-server /etc/redis/redis.conf --port 6379
  - composer install --no-interaction
  - composer update --no-interaction
  - ./vendor/bin/phinx migrate -e development
  - ./vendor/bin/phinx seed:run
  - sudo rabbitmqctl status

script:
  - ./vendor/bin/codecept run
