language: php
php:
- 7.2
- 7.3
services:
- mysql
- memcached
- redis-server
- rabbitmq
addons:
  apt:
    packages:
    - rabbitmq-server
sudo: false
env:
  global:
  - DATA_API_MYSQL_HOST: 127.0.0.1
  - DATA_API_MYSQL_PASS: ''
  - DATA_API_MYSQL_USER: root
  - DATA_API_MYSQL_NAME: gonano
  - DATA_API_MEMCACHED_HOST: 127.0.0.1
  - DATA_API_MEMCACHED_PORT: 11211
  - DATA_API_MEMCACHED_WEIGHT: 100
  - REDIS_HOST: 127.0.0.1
  - REDIS_PORT: 6379
  - APP_IP: api.baka.ld
  - APP_ENV: development
  - JWT_SECURITY: 0
  - GEWAER_APP_ID: 1
  - PHINX_CONFIG_DIR: "/home/scrutinizer/build/storage"
  - secure: l44Xhz1bubxBnfXIgOrilcZ4z5Z2VIZ6CBIodnAmigg34N7t5udVkoCHcVnR/tl4+uyu5QtNgo8l9OymBIr2IOFmazCLUNxWwCWQbiAkOCzGgfp2mEk950+zhfd2txVCGhFFJBwXPmS5Uq4HbN9EichQf0b04gnt2hfh8FhFqiQH+Imd9/qmCzEMLvzipfz5/Slb3cYn7xo/4DwlOfQvNkIioetLgJFt+K3jhat0gy81bCFwmNz6z3fAVyyMJM6Xp1fPYqgxSiAXoRxrZtttrlbQrTbu2ey4p+vHY5s2+CZHxo1pTQVwlt2f4reSGmxAvyuLIBOfSjwjF5Q6TSJf7BQQkYna14Qi4/aufJoEDadll8g8gQfHQ2GlmxM9w7EElyJltfJo4xSFwgQJ337D7RfWzXvAO24Jo1QSfc/z6gQqpT6v4qv++XuSdxPB5IqQsWaKTxv1AR8MuD6d7Lh+7NYlPyebpzECZyEpIm7fDgwkUhbdxngobfoMKfdhbc7EAGlSaiMjHoo+BqCiFVUlLixQgkoOJTFljGBzRUO+s4BiggWCeuCp8OTIVwRjarLWx1AcfL9UWfNEPMu4yR/H0bYu0ss0FjsRQkYGtTUt1jz/69a6dZp/tofo1eRH5f0vmqNT0TOOVcFO+s6aO+zVUMV/ks8nHuGX7FJe5miRkFE=
  - secure: emukGymU43y+K+Flf5b4XIYjrD1OxSgqpSVOIx8v3w9AUovweNbd/2FQ1eicMqPiDNvzArTK024PWh00X+FpHhCTRcutZzKAhpwNu2QkbROml0HXAH6zo6r6jC/n9GZkG8psDDZjJK1M39Iw07dQHD7Zl+kinaU7Yc2+84JAOfDA7VJx+zNosUB2Egk1JZutPPc33VnCdHOhbU+RTmXooShvTi06HcXJb5oizW/58C2NGR/KFL86G+UqNfG13fgxlfXG0pm2CMx7fCahZxOSpz7vV1dHwA3tgMEs3TCbCl1zHBzApzIpBaZDJc8xa80/VFJMJP8SXDHZhQxDizYL7hNN8cJRaRzu3pRMjzQ1mcuUWQSXHkWqSsl2Ox83k0UZIA5mfQlGZtIpEc8W6IGcWRH+ndYt9YpFZ1gbJvImimWCFiEwd3d+h726zx7msXtu6/ZpskW//yjG4oz6Rq+tUaV4rvTP401eHRn/8L2cIpC83LS+bwFg5HfQ4Hr/Kjov4JLJs5+DFs34mJI2a1BPcvxxsuIlSqDn/U6rHZFq9iSR9/aUotHwT4lqQ89y717I/u9cM0X6gyx8oCrr9DWd8QYTGqPL5TKTbHFl5gdQckp2sq5gMRPHoS1H3hwI5295C7s6TdJr/ci/BrfSa0wR+oSbNaJzLqa0+Wmbpmw2ISw=
cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
  - "~/cphalcon"
install:
- composer self-update
- cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git
  && cd cphalcon/build && ./install
- echo 'extension = "phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- php --ri phalcon
before_script:
- cd $TRAVIS_BUILD_DIR
- cp storage/ci/.env.example .env
- cp storage/ci/phinx.php.example phinx.php
- mysql -e "CREATE DATABASE gonano"
- sudo redis-server /etc/redis/redis.conf --port 6379
- composer install --no-interaction
- composer update --no-interaction
- "./vendor/bin/phinx migrate -e development"
- "./vendor/bin/phinx seed:run"
- sudo rabbitmqctl status
script:
- "./vendor/bin/codecept run"
