language: php

php:
  - 7.2
  - 7.3

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - ~/cphalcon

mysql:
  database: baka
  username: root
  password: password
  encoding: utf8

install:
  - composer self-update
  - cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install
