language: php

php:
  - 7.2
  - 7.3

services:
  - mysql
  - memcached
  - redis-server
  - rabbitmq

addons:
  apt:
    packages:
    - rabbitmq-server

sudo: false

env:
  global:
      - DATA_API_MYSQL_HOST: "127.0.0.1"
      - DATA_API_MYSQL_PASS: ""
      - DATA_API_MYSQL_USER: "root"
      - DATA_API_MYSQL_NAME: "gonano"
      - DATA_API_MEMCACHED_HOST: "127.0.0.1"
      - DATA_API_MEMCACHED_PORT: 11211
      - DATA_API_MEMCACHED_WEIGHT: 100
      - REDIS_HOST: "127.0.0.1"
      - REDIS_PORT: 6379
      - APP_IP: "api.baka.ld"
      - APP_ENV: development
      - JWT_SECURITY: 0
      - GEWAER_APP_ID: 1
      - PHINX_CONFIG_DIR: "/home/scrutinizer/build/storage"
      - secure: "gCdCeMAb8TYwDAHjpmTczEw0JTbgrjNKsoWB/uSYLL0E3ss0yfCVMBHxPV7uu5/25nKx3mmZdizNhZ8TXHY1PG4+rO0i17GYbZ0JyXwJiCcqtODtAwXPWDaf2O4yKEeCtzvunYLxy5Jqlo4v/jtedQj6RjxkyRjerzWGfvhTWlRYGtbSC3plyfA272ENFyQz5w9bDX9Qrs13+QgFr+d0IduIsjTShXoYWbNjHqswUGY2iR1uTwNGvpANpB9I6l9BD/p19u+MjThYYQeau2Zb2C/rNlhROt/XgEZJn2XamLtW1MUQuNP7Lo2/PcGrUyxcUtYI48JTHRU2UXaXe5Vgj8d8UVJi/pBXLjYCqvazZCmb/kdDbZijfc3cmYWXsHvjNY8B/8mprD46eAOSTLIZjC6hfCpUjH9q2u8Jl06iAMFkvrjIUgxFMUj5AocwKKZ7nT2LMmh/DswpxTsLmfvgGkRELiGu0ZvBBsBcfKZ7Z0u+XcmdgmYPZzv33meGhP/k40ML7ujSsQBBPQGQHsEI/awdllyC8B53ADG7mkCNVajEoVuzuktkmRKlhKPywdu3XfJwNinNSuLWTIL3poIhpGv+p5KEzAWthgEi+gxCVKIzkO2kxfHNZtGMiakkhj4aOE/2S6iNxFaxYMPdBzyTVVLK6yeJBeplPcp6QZtN+lo="
      - secure: "Tkl6OdznYKFsmlUnRKAVNNEjjSOvjIPUGxRVqP/oiom4Cp0isbAFqIkgxSauFGgXZI6RjCMF7RCIBzmj4oiDMM6mNiGGDbtCvTD2NeP/VVzrNTIfYaDWAVBH3lDmbofRhMQk143h7EdoguuBs2k8r7TYnivIu+oYxvzGYtuJQ2IgSMTX96EpH6Dlby5PKVQPW/eNZlwENFx4KSuc9nM8A1x2LElLc4J3wTiMSSNTR4ZeGWepPPhoR0ut8AaSN3tJNJf7yFKwAyHYWQvIPGuJ2NAv1IGPlEKcwYrRF2BizpJ8WS/P1X947CYa1kvnhrs8B4nLNgMKSKDBqc8iiorxhKlTWKbsaZu+GeKbshEVOAcoHL0gnQLta0KM4Fw6uW140ineyxL1CWuO4lINX8p8c+OX7pk4URpagQxqEe1ejawlSUVhCJJnUb0SK3xfQ+ILOoN/Ugu9UhegiJWQ5bhAIDhL+3wGg0TflYK2+YldVd17/6VOgCBiHoYrJUu4VuF0a21PuqXXihtPTMxiDwfy81yHdtdri0i+xduB91WXLN57rgeQmgjNDKx+Hdj86KPFzW7LCymVd7InnydYJZBOpcw/F2EfXWiX5VjnUAyc91jPA6QhCDAmsIj8NZFYPZyJP84DK6obEGlH7OMJFFhrBgmmFTO5qiqXmIqFp27irLw="

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - ~/cphalcon

install:
  - composer self-update
  - cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install
  - echo 'extension = "phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php --ri phalcon

before_script:
  - cd $TRAVIS_BUILD_DIR
  - cp storage/ci/.env.example .env
  - cp storage/ci/phinx.php.example phinx.php
  - mysql -e "CREATE DATABASE gonano"
  - sudo redis-server /etc/redis/redis.conf --port 6379
  - composer install --no-interaction
  - composer update --no-interaction
  - ./vendor/bin/phinx migrate -e development
  - ./vendor/bin/phinx seed:run
  - sudo rabbitmqctl status

script:
  - ./vendor/bin/codecept run
