language: php

php:
  - 7.2
  - 7.3

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - ~/cphalcon

before_install:
  - cp storage/ci/.env.example .env
  - cp storage/ci/phinx.php.example phinx.php
  - mysql -e "CREATE DATABASE gonano"
  - mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password');"
  - mysql -e "FLUSH PRIVILEGES"

install:
  - composer self-update
  - cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install
  - echo 'extension = "phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php --ri phalcon
  - cd $TRAVIS_BUILD_DIR
  - composer install --no-interaction
  - composer update --no-interaction
  - ./vendor/bin/phinx migrate -e development
  - ./vendor/bin/phinx seed:run

test:
  script:
    - ./vendor/bin/codecept run integration
