language: php

php:
  - 7.2
  - 7.3

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - APPLICATION_ENV="travis"
  matrix:
    - PHALCON_VERSION="2.0.11"
    - PHALCON_VERSION="2.0.10"
    - PHALCON_VERSION="2.0.9"
    - PHALCON_VERSION="2.0.8"
    - PHALCON_VERSION="2.0.7"
    - PHALCON_VERSION="2.0.6"
    - PHALCON_VERSION="2.0.5"

install:
  - composer self-update
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php --ri phalcon
  - composer install --prefer-source --no-interaction

before_script:
  - mysql -e 'CREATE DATABASE baka CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;' -uroot
  - cat tests/_data/dump.sql | mysql -uroot baka


after_script:
  #- mysql -e 'DROP DATABASE phanbook;' -uroot -ppassword__phanbook

script:
  - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 --ignore=core/common/ src/
  - vendor/bin/codecept build
  - vendor/bin/codecept run

addons:
  hosts:
    - db
    - phanbook.dev
    - localhost
