language: php

php:
  - 7.2
  - 7.3

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - ~/cphalcon

mysql:
  database: baka
  username: root
  password: password
  encoding: utf8

# env:
#   - DATA_API_MYSQL_HOST: "127.0.0.1"
#   - DATA_API_MYSQL_PASS: ""
#   - DATA_API_MYSQL_USER: "root"
#   - DATA_API_MYSQL_NAME: "baka"
#   - DATA_API_MEMCACHED_HOST: "127.0.0.1"
#   - DATA_API_MEMCACHED_PORT: 11211
#   - DATA_API_MEMCACHED_WEIGHT: 100
#   - REDIS_HOST: "127.0.0.1"
#   - REDIS_PORT: 6379
#   - APP_IP: "api.baka.ld"
#   - APP_ENV: development
#   - JWT_SECURITY: 0
#   - GEWAER_APP_ID: 1
#   - PHINX_CONFIG_DIR: "/home/scrutinizer/build/storage"

install:
  - composer self-update
  - cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install

# before_script:
#   - cd /home/scrutinizer/build
#   - cp storage/ci/.env.example .env
#   - cp storage/ci/phinx.php.example phinx.php

# script:
#   - mysql -e "CREATE DATABASE baka"
#   - mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password');"
#   - mysql -e "FLUSH PRIVILEGES"


# after_script:
#   #- mysql -e 'DROP DATABASE phanbook;' -uroot -ppassword__phanbook

# script:
#   - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 --ignore=core/common/ src/
#   - vendor/bin/codecept build
#   - vendor/bin/codecept run

# addons:
#   hosts:
#     - db
#     - phanbook.dev
#     - localhost
