language: php
php:
- 7.2
- 7.3
services:
- mysql
- memcached
- redis-server
- rabbitmq
addons:
  apt:
    packages:
    - rabbitmq-server
sudo: false
env:
  global:
  - DATA_API_MYSQL_HOST: 127.0.0.1
  - DATA_API_MYSQL_PASS: ''
  - DATA_API_MYSQL_USER: root
  - DATA_API_MYSQL_NAME: gonano
  - DATA_API_MEMCACHED_HOST: 127.0.0.1
  - DATA_API_MEMCACHED_PORT: 11211
  - DATA_API_MEMCACHED_WEIGHT: 100
  - REDIS_HOST: 127.0.0.1
  - REDIS_PORT: 6379
  - APP_IP: api.baka.ld
  - APP_ENV: development
  - JWT_SECURITY: 0
  - GEWAER_APP_ID: 1
  - PHINX_CONFIG_DIR: "/home/scrutinizer/build/storage"
  - secure: Zc6m/dyXQHl1OqKvbbIjqnYsHyEhlxRqqWZW3yhn0YQ9dOShi7rX08kHgDItaSFSNgFnXT3v+mHNulxaRTCUBDPhcSsqQ7KjFDzjLmPd/ThqkkIAFZhNtQQuvbtCzhtsGlOgIPT6GlS0qy/aj7RUY+Kc8xCi0QHWVKCrLaOrXdYbLPnarwTaDbf8DT0S3KewsyFJLV63bTOhAYJ4XvAgR77R90rclelaarlx0BdHJa3w4Wd3gs/flpD9A76CmHspQ5xBavAsH8jQlPd2uAFWfOSczxCIUwP0+gArVvda6Dt3wUg0lgAHh2Lb0KL7kNN1MbPDPSVAcjjfbgeBpU5XMf56afgW9v3eI3fUpA7yEAX+BJjWtTQTzMxP9Bk3cJGjSgEg7jPzc3yAw4hvl5Im/L+0+mbCym51XYC3B70ZyGhbl2vI/W9Qqtp3VjrWmjk+aJdLnjbds1+YQ4Ir6tRuxGpzqAUxBqWvKHEU2rRpyE2rFEYKQUZ0e3YVpVp+8grfKqlYDcamFbYZ7qcmlBm9Cd7pq0k54aWfXyT5xsfsunpcuh2gGYLvZUPIzzO19bM8rl/AYnbD0mkyt122HBGGU9BmbACeQaorHdy+1duQCia/UZVjU2FFr+m/9evXiSfPrpUhnxfnw86Tn5duVMDACNGH/74A07A0fR78kShnERM=
  - secure: UarWixY62dHt8cSAJf0b1cUYOzbw+mrh2vMrravEc3LjuNk/pOrsQ54E30xTQ1amqVYCbBT+LquSIjhpziq+kDCXAHcQo7Hyca9oduKUAipxa19+7GT9nLQ4SkdgJ9SccfrpmovdHs6SpM83uuTEgsQ6UIflyj9mcfwmOHQJXd+2U/bPK7ncqnm1zQdJ4J/W/brsuzpJxjl+loqIIMyb+cma4tSoNuSp1GCQTAfRPgsNe1zqmYHvGQxG9nwvzjNyiU6dApWE9cAxIhwmU0NDpG4coJs3VzOrZGwFdeG7Y2Y3VHAo9rGwMm+ReifhjJ/djYQBsrf294muml6OFrB7VGroBPiXGt2j4x7U4Xbf76n06swzKNKHX16AGA5VAWWd66ypo6r1hAqaN/VyKMc1LjsLewgB0HrY05zURcq6WfIgw01WGKBMeefUBhMsSvm0kdh3VCGy1lG3C7B6ld02JmLcXVjCvc6Jt1wsgddQmeBADcUbOPo8DvGrIi0ok9B6aT6pTAkujntz/FePYfIbqnrUmLdw5HUzoWzgVtGnxG69iuKTJ5eh2+mD/Y2kWxb4Weyg2t7wQCSbH/VTHZqzG6YcvFabkeKgRlppK3kukh9A9ziUFwYIW5te+NADUwWWEp6AP2eXTmHnEqpDXN2fywK2+hGKF2KOmAJAGyXhK/Q=
cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
  - "~/cphalcon"
install:
- composer self-update
- cd ~/ && rm -rf cphalcon && git clone -b 3.4.x -q --depth=1 https://github.com/phalcon/cphalcon.git
  && cd cphalcon/build && ./install
- echo 'extension = "phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
- php --ri phalcon
before_script:
- cd $TRAVIS_BUILD_DIR
- cp storage/ci/.env.example .env
- cp storage/ci/phinx.php.example phinx.php
- mysql -e "CREATE DATABASE gonano"
- sudo redis-server /etc/redis/redis.conf --port 6379
- composer install --no-interaction
- composer update --no-interaction
- "./vendor/bin/phinx migrate -e development"
- "./vendor/bin/phinx seed:run"
- sudo rabbitmqctl status
script:
- "./vendor/bin/codecept run"
